### ISSUE TITLE
Unrecognized runtime "Julia"

### ISSUE THREAD

**Issue by pjgoodall** [ageron/julia_notebooks#3]
Hi,
I cannot run this notebook, because there is no 'Julia' runtime type, the session  defaults to python. And fails to run.

![image](https://user-images.githubusercontent.com/719962/126052904-668e6412-3df8-40b0-b578-5fedd4b2f35f.png)

```
versioninfo()
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-3-a67619e8ecad> in <module>()
----> 1 versioninfo()

NameError: name 'versioninfo' is not defined
```

**Comment by ageron** [comment]
Hi @pjgoodall ,

Please make sure you follow the installation instructions step by step, in particular make sure you reload the page after running the first code cell. For your convenience, here are the installation instructions:

1. Work on a copy of the notebook: File > Save a copy in Drive (you will need a Google account). Alternatively, you can download the notebook using File > Download .ipynb, then upload it to Colab.
2. Execute the first code cell (click on it and press Ctrl+Enter) to install Julia, IJulia (the Jupyter kernel for Julia) and other packages. You can update JULIA_VERSION and the other parameters, if you know what you're doing. Installation takes 2-3 minutes.
3. Reload the page (press Ctrl+R, or ⌘+R, or the F5 key) and continue to the Checking the Installation section.
* Note: If your Colab Runtime gets reset (e.g., due to inactivity), repeat steps 2 and 3.

To be sure, I just followed these steps, and everything ran smoothly. 👍 

Hope this helps.
